import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.Spacing.lg,
    },
    modalContent: {
      width: '100%',
      maxHeight: '85%',
      borderRadius: 32,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.75)',
      overflow: 'hidden',
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
    },
    desktopModal: {
      width: 600,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: theme.Spacing.lg,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(0, 104, 117, 0.1)',
    },
    ticketNum: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '800',
      color: theme.Colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    modalTitle: {
      fontSize: theme.Typography.bodyLg?.fontSize || 18,
      fontWeight: '900',
      color: theme.Colors.onSurface,
      marginTop: 2,
    },
    closeButton: {
      padding: 6,
    },
    loadingContainer: {
      padding: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollBody: {
      padding: theme.Spacing.lg,
    },
    badgesRow: {
      flexDirection: 'row',
      gap: theme.Spacing.sm,
      marginBottom: 20,
    },
    badge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
    },
    badgeText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    infoCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.65)',
      borderRadius: 20,
      padding: theme.Spacing.md,
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '700',
      color: theme.Colors.primary,
      marginBottom: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    descriptionText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      lineHeight: 20,
    },
    metaGrid: {
      flexDirection: 'row',
      marginTop: theme.Spacing.md,
      paddingTop: theme.Spacing.md,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      gap: theme.Spacing.lg,
    },
    metaItem: {
      flex: 1,
    },
    metaLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginBottom: 2,
      fontWeight: '600',
    },
    metaValue: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.onSurface,
    },
    actionsContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.55)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.75)',
      borderRadius: 20,
      padding: theme.Spacing.md,
      marginBottom: 20,
    },
    actionButtonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.Spacing.sm,
    },
    actionBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    btnInProg: {
      backgroundColor: theme.Colors.primary,
    },
    btnResolve: {
      backgroundColor: theme.Colors.primary,
    },
    btnEscalate: {
      backgroundColor: theme.Colors.error,
    },
    actionBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.surfaceContainerLowest,
    },
    escalateInputContainer: {
      marginTop: 12,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      paddingTop: 12,
    },
    escalateInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.1)',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      marginBottom: 10,
    },
    escalateActionButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: theme.Spacing.sm,
    },
    cancelBtn: {
      paddingHorizontal: 12,
      paddingVertical: theme.Spacing.sm,
    },
    cancelBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '700',
    },
    confirmEscalateBtn: {
      backgroundColor: theme.Colors.error,
      paddingHorizontal: 14,
      paddingVertical: theme.Spacing.sm,
      borderRadius: 10,
    },
    confirmEscalateText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.surfaceContainerLowest,
    },
    timelineSection: {
      marginTop: 10,
    },
    timelineItem: {
      flexDirection: 'row',
      gap: theme.Spacing.md,
      marginBottom: theme.Spacing.md,
    },
    timelineLineWrapper: {
      alignItems: 'center',
    },
    timelineDot: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: 'rgba(0,104,117,0.1)',
      marginTop: theme.Spacing.xs,
    },
    timelineContent: {
      flex: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.4)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.55)',
      borderRadius: 12,
      padding: 12,
    },
    timelineHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: theme.Spacing.xs,
    },
    authorName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.onSurface,
    },
    timelineDate: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '600',
    },
    timelineBody: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      lineHeight: 18,
    },
    emptyTimelineText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontStyle: 'italic',
      textAlign: 'center',
      marginTop: 10,
    },
    commentInputWrapper: {
      flexDirection: 'row',
      padding: theme.Spacing.md,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      backgroundColor: 'rgba(255, 255, 255, 0.35)',
      alignItems: 'center',
      gap: 12,
    },
    commentInput: {
      flex: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.65)',
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.15)',
      borderRadius: 18,
      paddingHorizontal: theme.Spacing.md,
      paddingVertical: 10,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      maxHeight: 100,
    },
    sendButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendButtonDisabled: {
      backgroundColor: 'rgba(0, 104, 117, 0.15)',
    },
  });
