import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  root: { flex: 1 },
  safeArea: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 120, gap: 16 },
  scrollContentDesktop: { padding: 32, maxWidth: 1280, width: '100%', alignSelf: 'center' },

  desktopHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 16, marginBottom: 4 },
  kickerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  kicker: { fontSize: theme.Typography.LabelSmall.fontSize, fontWeight: '800', letterSpacing: 1.2, color: theme.Colors.primary, textTransform: 'uppercase' },
  propertyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: 'rgba(0,104,117,0.08)',
  },
  propertyBadgeText: { fontSize: theme.Typography.LabelSmall.fontSize, fontWeight: '700', color: theme.Colors.primary },
  desktopTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginTop: 10 },
  desktopTitleWrapper: { flex: 1 },
  desktopTitle: { fontSize: theme.Typography.headlineLg.fontSize, fontWeight: '900', color: theme.Colors.onSurface, letterSpacing: -0.5 },
  desktopSub: { fontSize: theme.Typography.BodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: 4, fontWeight: '600' },
  desktopActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },

  btnPrimary: { borderRadius: 100, overflow: 'hidden' },
  btnPrimaryInner: { height: 46, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  btnText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '800', letterSpacing: 0.5 },

  mobileHeader: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8 },
  mobileTitle: { fontSize: theme.Typography.headlineMd.fontSize, fontWeight: '800', color: theme.Colors.onSurface, letterSpacing: -0.5 },
  mobileSub: { fontSize: theme.Typography.BodySmall.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: 2, fontWeight: '600' },

  filterBar: { flexDirection: 'row', paddingHorizontal: 16, gap: 12, alignItems: 'center', marginTop: 10 },
  filterBarDesktop: { paddingHorizontal: 0, marginTop: 24 },
  searchWrapper: { flex: 1, position: 'relative' },
  searchIcon: { position: 'absolute', left: 14, top: 12, zIndex: 5 },
  searchInput: {
    height: 44,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.75)',
    paddingLeft: 44,
    paddingRight: 16,
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '600',
    outlineWidth: 0,
  },
  propertySelectWrapper: { width: 190 },

  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  statCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  statHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  statTitle: { fontSize: theme.Typography.LabelSmall.fontSize, fontWeight: '800', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },
  statIcon: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  statVal: { fontSize: theme.Typography.headlineSm.fontSize, fontWeight: '900', color: theme.Colors.onSurface },

  tabsRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.06)', marginTop: 8, paddingHorizontal: 16 },
  tabsRowDesktop: { paddingHorizontal: 0, marginTop: 16 },
  tabBtn: { paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 2, borderBottomColor: 'transparent', marginRight: 16 },
  activeTabBtn: { borderBottomColor: theme.Colors.primary },
  tabText: { fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '700', color: theme.Colors.onSurfaceVariant },
  activeTabText: { color: theme.Colors.primary, fontWeight: '800' },

  sectionCard: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    padding: 24,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    overflow: 'hidden',
  },
  sectionTitle: { fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '800', color: theme.Colors.onSurface, marginBottom: 16 },

  gridContainer: { gap: 16 },
  gridContainerDesktop: { flexDirection: 'row', flexWrap: 'wrap', gap: 24 },
  gridItemDesktop: { width: '48%' },

  leaseCard: {
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    padding: 20,
    gap: 16,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardTitle: { fontSize: theme.Typography.TitleMedium.fontSize, fontWeight: '800', color: theme.Colors.onSurface },
  cardSubtitle: { fontSize: theme.Typography.BodySmall.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: 2, fontWeight: '600' },

  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  infoCol: { flex: 1, minWidth: 120 },
  infoLabel: { fontSize: theme.Typography.LabelSmall.fontSize - 2, fontWeight: '800', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },
  infoValue: { fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '700', color: theme.Colors.onSurface, marginTop: 4 },

  actionRow: { flexDirection: 'row', gap: 12, marginTop: 6 },
  btnSecondary: {
    flex: 1,
    height: 42,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(0,104,117,0.04)',
  },
  btnSecondaryText: { color: theme.Colors.primary, fontSize: theme.Typography.BodySmall.fontSize, fontWeight: '800' },

  btnActionDestructive: {
    flex: 1,
    height: 42,
    borderWidth: 1.5,
    borderColor: theme.Colors.error,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(229,57,53,0.04)',
  },
  btnActionDestructiveText: { color: theme.Colors.error, fontSize: theme.Typography.BodySmall.fontSize, fontWeight: '800' },

  btnActionSuccess: {
    flex: 1,
    height: 42,
    borderRadius: 100,
    overflow: 'hidden',
  },
  btnActionSuccessInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  btnActionSuccessText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.BodySmall.fontSize, fontWeight: '800' },

  emptyContainer: { padding: 40, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyText: { fontSize: theme.Typography.BodyLarge.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '600' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalCard: { width: '100%', backgroundColor: theme.Colors.surfaceContainerLowest, borderRadius: 28, overflow: 'hidden', borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.9)' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 24, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.06)' },
  modalKicker: { fontSize: theme.Typography.LabelSmall.fontSize, fontWeight: '800', letterSpacing: 1, color: theme.Colors.onSurfaceVariant },
  modalTitle: { fontSize: theme.Typography.TitleLarge.fontSize, fontWeight: '800', color: theme.Colors.onSurface, marginTop: 4 },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(0,0,0,0.03)', alignItems: 'center', justifyContent: 'center' },
  modalBody: { padding: 24, gap: 16 },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, padding: 24, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.06)' },

  cancelBtn: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 100 },
  cancelBtnText: { fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '700', color: theme.Colors.onSurfaceVariant },
  submitBtn: { borderRadius: 100, overflow: 'hidden' },
  submitBtnInner: { paddingVertical: 12, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  submitBtnText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '800' },

  input: {
    height: 48,
    backgroundColor: 'rgba(0,0,0,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(0,104,117,0.15)',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '600',
    outlineWidth: 0,
  },
  label: { fontSize: theme.Typography.LabelSmall.fontSize, fontWeight: '700', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },

  // Pagination Styles
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 4,
    marginTop: 8,
  },
  paginationRowDesktop: {
    marginTop: 16,
    paddingHorizontal: 0,
  },
  pageBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  pageBtnDisabled: {
    opacity: 0.5,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  pageBtnText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
    fontFamily: 'Inter',
  },
  pageBtnTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  pageNumberPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  pageNumberText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    fontFamily: 'Inter',
  },
  actionBtnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'transparent',
  },
  actionBtnText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
  },
  actionBtnPrimary: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  actionBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  actionBtnTextPrimary: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
  },
  actionBtnTextBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  forfeitText: {
    color: theme.Colors.error,
    fontWeight: '700',
    fontSize: theme.Typography.BodySmall.fontSize,
  },
  refundText: {
    color: theme.Colors.primary,
    fontWeight: '700',
    fontSize: theme.Typography.BodySmall.fontSize,
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: theme.Typography.TitleLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    marginTop: 8,
  },
  emptySubtitle: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    textAlign: 'center',
    lineHeight: 20,
  },
  listContainer: {
    gap: 16,
  },
  leaseCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  tenantAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaseMainInfo: {
    flex: 1,
  },
  tenantName: {
    fontSize: theme.Typography.TitleMedium.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  tenantContact: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  detailValueSecondary: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
  },
  unitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  unitChipSelected: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    borderColor: theme.Colors.primary,
  },
  unitChipText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  unitChipTextSelected: {
    color: theme.Colors.primary,
    fontWeight: '700',
  },
  twoCol: {
    flexDirection: 'row',
    gap: 16,
    width: '100%',
  },
  detailLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize - 2,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.5,
  },
  detailItem: {
    flex: 1,
    minWidth: 100,
  },
  detailValue: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
    marginTop: 4,
  },
  leaseActionsCol: {
    flexDirection: 'column',
    gap: 8,
    minWidth: 140,
  },
  actionBtnOutlineDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1.5,
    borderColor: theme.Colors.error,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'transparent',
  },
  actionBtnTextDanger: {
    color: theme.Colors.error,
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
  },
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
  },
  paginationInfo: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  paginationControls: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  tenantAvatarText: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
  },
  leaseTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  unitBadge: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(0,104,117,0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  unitBadgeText: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
  },
  leaseDetailsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 12,
  },
  statsRowDesktop: {
    flexDirection: 'row',
    gap: 20,
  },
  statCardDesktop: {
    minWidth: 220,
  },
  statIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '900',
    marginTop: 12,
  },
  statLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.5,
    marginTop: 4,
  },
  statHelper: {
    fontSize: theme.Typography.BodySmall.fontSize - 2,
    color: theme.Colors.outline,
    marginTop: 2,
  },
  tabBar: {
    flexDirection: 'row',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
    paddingBottom: 4,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 100,
    overflow: 'hidden',
    position: 'relative',
  },
  tabActive: {},
  tabTextActive: {
    color: theme.Colors.onPrimary,
    fontWeight: '800',
  },
  tabBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  tabBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  tabBadgeText: {
    fontSize: theme.Typography.LabelSmall.fontSize - 2,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  tabBadgeTextActive: {
    color: theme.Colors.onPrimary,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
  },
  panel: {
    borderRadius: 28,
    padding: 24,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  loadingBox: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  leaseCardAlert: {
    borderColor: 'rgba(229,57,53,0.3)',
    backgroundColor: 'rgba(229,57,53,0.02)',
  },
  alertStripe: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 4,
  },
  title: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
    marginTop: 4,
  },
  subtitle: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  createBtnWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
  },
  createBtn: {
    height: 46,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  createBtnText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
});
