import { StyleSheet, Platform } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  container: {
    padding: theme.Spacing.containerPadding,
    paddingTop: Platform.OS === 'web' ? 24 : 88,
  },
  containerDesktop: {
    paddingTop: 24,
    paddingHorizontal: 32,
    paddingBottom: 40,
    width: '100%',
  },
  kpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 20,
  },
  kpiCard: {
    flex: 1,
    minWidth: 220,
    padding: 18,
    borderRadius: 16,
  },
  kpiHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  kpiLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: theme.Colors.onSurfaceVariant,
  },
  kpiValue: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '900',
    color: theme.Colors.onSurface,
    marginBottom: 4,
  },
  kpiSub: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  glassCard: {
    marginBottom: 20,
    padding: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
  },
  sectionTitle: {
    ...theme.Typography.headlineMd,
    color: theme.Colors.onBackground,
  },
  sectionSubtitle: {
    ...theme.Typography.labelMuted,
    color: theme.Colors.outline,
    marginTop: 4,
    maxWidth: 540,
  },
  monthSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderRadius: theme.Rounded.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  monthArrow: {
    padding: 4,
  },
  monthLabel: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onBackground,
    marginHorizontal: 12,
    minWidth: 130,
    textAlign: 'center',
  },
  propertyTabsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
    paddingTop: 16,
  },
  statusChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  propertyTabs: {
    flexDirection: 'row',
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
    paddingTop: 16,
  },
  propertyTabsContent: {
    gap: 8,
  },
  propTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: theme.Rounded.full,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  propTabActive: {
    backgroundColor: theme.Colors.primary,
    borderColor: theme.Colors.primary,
  },
  propTabText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  propTabTextActive: {
    color: theme.Colors.surfaceContainerLowest,
  },
  filterControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  searchBox: {
    flex: 1,
    minWidth: 260,
    height: 44,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    outlineWidth: 0,
  },
  statusChipsContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  statusChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  statusChipActive: {
    backgroundColor: theme.Colors.primary,
    borderColor: theme.Colors.primary,
  },
  statusChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  statusChipTextActive: {
    color: theme.Colors.surfaceContainerLowest,
  },
  listCard: {
    padding: 20,
  },
  listCardDesktop: {
    padding: 0,
  },
  table: {
    width: '100%',
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  headerCell: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.outline,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  rowMobile: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderBottomWidth: 0,
  },
  cell: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onBackground,
  },
  tenantAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tenantAvatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '800',
    fontSize: theme.Typography.bodyMedium.fontSize,
  },
  downloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.2)',
  },
  downloadBtnText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  mobileCard: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    marginBottom: 12,
  },
  mobileCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mobileTenantName: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onBackground,
  },
  mobileCardDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  mobileDetailLabel: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.outline,
    fontWeight: '500',
  },
  mobileDueDate: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
  },
  mobileAmountsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.04)',
  },
  mobileAmount: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onBackground,
  },
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    flexWrap: 'wrap',
    gap: 12,
  },
  paginationInfo: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  paginationActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    gap: 2,
  },
  pageBtnDisabled: {
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderColor: theme.Colors.surfaceContainer,
  },
  pageBtnText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  pageBtnTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  pageNumberBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
  },
  pageNumberText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  center: {
    padding: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
});

