import { Platform, StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  container: {
    padding: Theme.Spacing.containerPadding,
    paddingTop: Platform.OS === 'web' ? 24 : 88,
  },
  containerDesktop: {
    paddingTop: 24,
  },
  heroSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  heroTitle: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '900',
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
    maxWidth: 600,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 10,
  },
  actionPillBtn: {
    borderRadius: 100,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  actionPillGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  actionPillText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  hubGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 28,
  },
  hubCardTouch: {
    flex: 1,
    minWidth: 240,
  },
  hubCard: {
    padding: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  hubCardActive: {
    borderColor: theme.Colors.primary,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
  },
  hubCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  hubIconHalo: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  hubBadgeText: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
  },
  hubCardTitle: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    marginBottom: 4,
  },
  hubCardDesc: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    lineHeight: 17,
  },
  sectionContainer: {
    flex: 1,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: theme.Typography.TitleLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  sectionSub: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  rolesGrid: {
    gap: 14,
  },
  roleCard: {
    padding: 20,
    borderRadius: 18,
  },
  roleCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  roleTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  roleName: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  customRolePill: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.2)',
  },
  customRolePillText: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
  },
  systemRolePill: {
    backgroundColor: 'rgba(107, 122, 125, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(107, 122, 125, 0.2)',
  },
  systemRolePillText: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  roleDesc: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    lineHeight: 19,
  },
  roleCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.05)',
  },
  permCountTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 104, 117, 0.06)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  permCountText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  configureBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  configureBtnDisabled: {
    backgroundColor: theme.Colors.surfaceContainerLow,
  },
  configureBtnText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  configureBtnTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  invitesGrid: {
    gap: 14,
  },
  inviteCard: {
    padding: 20,
    borderRadius: 18,
  },
  inviteCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  codeCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.2)',
  },
  inviteCode: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '900',
    color: theme.Colors.primary,
    letterSpacing: 1.5,
  },
  inviteMetaRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  inviteMetaCol: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  inviteMetaLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    marginBottom: 4,
    letterSpacing: 0.8,
  },
  inviteMetaVal: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  copyKeyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.3)',
  },
  copyKeyBtnText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  prefGrid: {
    gap: 16,
  },
  prefCard: {
    padding: 22,
    borderRadius: 20,
  },
  prefCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  prefCardTitle: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  prefItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.05)',
  },
  prefItemName: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  prefItemDesc: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  prefBadgeActive: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.2)',
  },
  prefBadgeText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 640,
    maxHeight: '85%',
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  modalTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  modalSub: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  closeIconBtn: {
    padding: 6,
    borderRadius: 10,
    backgroundColor: theme.Colors.surfaceContainer,
  },
  modalBody: {
    padding: 24,
  },
  categoryBlock: {
    marginBottom: 20,
  },
  categoryHeading: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1.1,
    marginBottom: 10,
  },
  permCheckRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.04)',
  },
  permCheckRowDisabled: {
    opacity: 0.4,
  },
  permCheckInfo: {
    flex: 1,
    paddingRight: 12,
  },
  permCheckName: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  permCheckNameDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  permCheckDesc: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  inputLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: theme.Colors.onSurfaceVariant,
    marginBottom: 6,
  },
  modalTextInput: {
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurface,
    backgroundColor: theme.Colors.surfaceContainerLow,
    marginBottom: 16,
    outlineWidth: 0,
  },
  roleChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  roleSelectChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    backgroundColor: theme.Colors.surfaceContainerLow,
  },
  roleSelectChipActive: {
    borderColor: theme.Colors.primary,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
  },
  roleSelectChipText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  roleSelectChipTextActive: {
    color: theme.Colors.primary,
  },
  modalFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  modalPrimaryBtn: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  modalBtnGradient: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  modalBtnText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  centerLoading: {
    padding: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingSub: {
    marginTop: 12,
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
});
