import { StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: { flex: 1 },
  desktopShell: { flex: 1, flexDirection: 'row' },
  sidebar: {
    width: 260, height: '100%', paddingHorizontal: 20, paddingTop: theme.Spacing.xl, paddingBottom: theme.Spacing.lg,
    borderRightWidth: 1, borderRightColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill, overflow: 'hidden',
  },
  sidebarBrand: { marginBottom: 54 },
  sidebarBrandTitle: { fontSize: theme.Typography.displaySmall.fontSize, fontWeight: '800', lineHeight: 40, color: theme.Colors.primary },
  sidebarBrandSub: { fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '700', letterSpacing: 2, color: theme.Colors.onSurfaceVariant, marginTop: theme.Spacing.xs },
  sidebarNav: { gap: 14 },
  sidebarLink: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.md, paddingHorizontal: 18, borderRadius: Theme.Rounded.lg },
  sidebarLinkActive: { backgroundColor: 'rgba(0, 224, 255, 0.10)', borderRightWidth: 4, borderRightColor: theme.Colors.primaryContainer },
  sidebarLinkText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '700', letterSpacing: 1.6, color: theme.Colors.onSurface },
  sidebarLinkTextActive: { color: theme.Colors.primary },
  sidebarFooter: { marginTop: 'auto', borderTopWidth: 1, borderTopColor: theme.Colors.outlineVariant, paddingTop: 28, gap: 10 },
  upgradeButton: { borderRadius: Theme.Rounded.lg, overflow: 'hidden', marginBottom: 14, shadowColor: theme.Colors.secondary, shadowOpacity: 0.24, shadowRadius: 16, shadowOffset: { width: 0, height: 8 } },
  upgradeGradient: { paddingVertical: theme.Spacing.md, alignItems: 'center' },
  upgradeText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '800' },
  desktopMain: { flex: 1, minWidth: 0 },
  topbar: { minHeight: 82, paddingHorizontal: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: theme.Colors.glassStroke, backgroundColor: theme.Colors.glassFill, overflow: 'hidden' },
  topbarTabs: { flexDirection: 'row', gap: 34, alignItems: 'center' },
  topbarTab: { fontSize: theme.Typography.bodyLg.fontSize, color: theme.Colors.onSurface },
  compactTopbarTitle: { color: theme.Colors.primary, fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '700' },
  topbarRight: { flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.md },
  searchBox: { minWidth: 260, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: theme.Spacing.md, paddingVertical: 12, borderRadius: Theme.Rounded.xl, borderWidth: 1, borderColor: theme.Colors.glassStroke, backgroundColor: theme.Colors.glassFill },
  searchPlaceholder: { color: theme.Colors.onSurfaceVariant, fontSize: theme.Typography.bodyMedium.fontSize },
  topIcon: { width: 46, height: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke },
  avatar: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.Colors.primaryContainer },
  avatarText: { color: theme.Colors.primary, fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '800' },
  desktopContent: { paddingTop: 24, paddingHorizontal: 32, paddingBottom: 40 },
  desktopInner: { width: '100%', flex: 1 },
  pageHeader: { marginBottom: 20 },
  pageHeaderRow: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  desktopSaveButtonWrapper: { borderRadius: 100, overflow: 'hidden', shadowColor: theme.Colors.secondary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.25, shadowRadius: 12, elevation: 4 },
  desktopSaveButton: { flexDirection: 'row', paddingHorizontal: theme.Spacing.lg, height: 46, justifyContent: 'center', alignItems: 'center', gap: theme.Spacing.sm },
  desktopSaveButtonText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '700' },
  pageTitle: { fontSize: theme.Typography.headlineLg.fontSize, fontWeight: '800', color: theme.Colors.onBackground, lineHeight: 38 },
  pageSubtitle: { marginTop: theme.Spacing.xs, fontSize: theme.Typography.bodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, maxWidth: 620 },
  sectionCard: { padding: theme.Spacing.xl, borderRadius: 24, backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke, overflow: 'hidden', shadowColor: theme.Colors.primary, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.05, shadowRadius: 30, elevation: 3 },
  desktopGrid: { flexDirection: 'row', alignItems: 'stretch', gap: theme.Spacing.lg },
  desktopGridStacked: { flexDirection: 'column' },
  composerColumn: { flex: 1, minWidth: 0, width: '100%' },
  historyColumn: { flex: 1.12, minWidth: 0, width: '100%' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 18, gap: theme.Spacing.md },
  sectionHeaderCopy: { flexShrink: 1, minWidth: 0 },
  sectionTitle: { fontSize: theme.Typography.titleLarge.fontSize, fontWeight: '700', color: theme.Colors.onSurface },
  sectionSubtitle: { marginTop: 5, fontSize: theme.Typography.bodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, maxWidth: 520 },
  badgeRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12, alignSelf: 'flex-start', maxWidth: '100%' },
  statsBadge: { paddingVertical: theme.Spacing.sm, paddingHorizontal: 12, borderRadius: Theme.Rounded.lg, backgroundColor: 'rgba(0, 114, 255, 0.1)', maxWidth: '100%' },
  statsBadgeText: { color: theme.Colors.secondary, fontWeight: '700', fontSize: theme.Typography.bodySmall.fontSize, flexShrink: 1 },
  formGroup: { marginBottom: 20 },
  eyebrow: { color: theme.Colors.primary, fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '700', letterSpacing: 2, marginBottom: 7 },
  inputLabel: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', letterSpacing: 1.8, color: theme.Colors.primary, marginBottom: 10 },
  textInput: { minHeight: 58, borderWidth: 1, borderColor: theme.Colors.glassStroke, borderRadius: 12, paddingHorizontal: theme.Spacing.md, paddingVertical: 14, backgroundColor: theme.Colors.glassFill, color: theme.Colors.onSurface, fontSize: theme.Typography.bodyLarge.fontSize },
  textarea: { minHeight: 154 },
  chipRow: { flexDirection: 'row', gap: 10, paddingVertical: 6 },
  chip: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 24, backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke, flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.sm },
  chipActive: { backgroundColor: theme.Colors.secondary, borderColor: theme.Colors.secondary },
  chipText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', color: theme.Colors.onSurfaceVariant },
  chipTextActive: { color: theme.Colors.surfaceContainerLowest },
  emptyStateText: { color: theme.Colors.onSurfaceVariant, fontSize: theme.Typography.bodyMedium.fontSize, marginTop: 10 },
  sendButton: { marginTop: 12, borderRadius: 14, overflow: 'hidden' },
  sendButtonDisabled: { opacity: 0.5 },
  sendButtonGradient: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 18 },
  sendButtonText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodyLarge.fontSize, fontWeight: '700' },
  historyList: { gap: theme.Spacing.md },
  historyCard: { marginBottom: 0, borderRadius: 0, backgroundColor: theme.Colors.surfaceContainerLowest, borderTopWidth: 1, borderTopColor: theme.Colors.outlineVariant, paddingVertical: 20, paddingHorizontal: theme.Spacing.xs },
  historyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  historyMeta: { fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '700', color: theme.Colors.onSurfaceVariant },
  historyTitle: { fontSize: theme.Typography.titleMedium.fontSize, fontWeight: '700', color: theme.Colors.primary, marginBottom: theme.Spacing.sm },
  historyContent: { fontSize: theme.Typography.bodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, lineHeight: 20, marginBottom: 14 },
  historyFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  historyTimestamp: { fontSize: theme.Typography.bodySmall.fontSize, color: theme.Colors.onSurfaceVariant },
  historyBadge: { fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '700', color: theme.Colors.primary },
  categoryBadge: { paddingVertical: 5, paddingHorizontal: 11, borderRadius: 14 },
  categoryText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '700' },
  centerRow: { alignItems: 'center', justifyContent: 'center', paddingVertical: theme.Spacing.xl },
  emptyStateCard: { alignItems: 'center', justifyContent: 'center', padding: theme.Spacing.xl, borderRadius: Theme.Rounded.xl, backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke },
  safeArea: { flex: 1 },
  mobileHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: theme.Spacing.md, backgroundColor: theme.Colors.glassFill, borderBottomWidth: 1, borderBottomColor: theme.Colors.glassStroke },
  mobileHeaderTitle: { fontSize: theme.Typography.titleLarge.fontSize, fontWeight: '800', color: theme.Colors.onBackground, fontFamily: 'Inter' },
  toggleHistoryBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, backgroundColor: 'rgba(0, 104, 117, 0.08)' },
  toggleHistoryText: { fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '700', color: theme.Colors.primary, fontFamily: 'Inter' },
  mobileTitle: { fontSize: theme.Typography.titleLarge.fontSize, fontWeight: '700', color: theme.Colors.primary },
  mobileSubtitle: { marginTop: 2, color: theme.Colors.onSurfaceVariant, fontSize: theme.Typography.bodySmall.fontSize },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  iconButton: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke },
  mobileAvatar: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.Colors.primaryContainer },
  mobileAvatarText: { color: theme.Colors.primary, fontWeight: '800' },
  mobileContent: { paddingHorizontal: theme.Spacing.md, paddingTop: 18, paddingBottom: 40, gap: 18 },
  segmentContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.Spacing.sm, marginTop: theme.Spacing.xs },
  segmentButtonWrapper: { minWidth: '30%', flexGrow: 1 },
  segmentButtonGradient: { paddingVertical: 10, paddingHorizontal: theme.Spacing.sm, alignItems: 'center', borderRadius: 10, borderWidth: 1, borderColor: 'transparent' },
  segmentButtonInactive: { paddingVertical: 10, paddingHorizontal: theme.Spacing.sm, alignItems: 'center', borderRadius: 10, backgroundColor: theme.Colors.glassFill, borderWidth: 1, borderColor: theme.Colors.glassStroke },
  segmentText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', color: theme.Colors.onSurfaceVariant },
  segmentTextActive: { color: theme.Surface.card, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '700' },
  segmentRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  headerIconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.Colors.glassFill, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: theme.Colors.glassStroke },
  headerRightActions: { flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.sm },
});
