import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(255, 255, 255, 0.45)',
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  compactTitleText: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontFamily: 'Inter',
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  card: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
    padding: 24,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  sectionTitle: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    color: theme.Colors.primary,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 18,
    gap: 8,
  },
  label: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
  },
  input: {
    height: 48,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: theme.Typography.BodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    fontWeight: '600',
    outlineWidth: 0,
  },
  inputWithIcon: {
    height: 48,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 12,
    paddingLeft: 16,
    paddingRight: 46,
    fontSize: theme.Typography.BodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    fontWeight: '600',
    width: '100%',
    outlineWidth: 0,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  inputIcon: {
    position: 'absolute',
    right: 16,
    top: 14,
  },
  row: {
    flexDirection: 'row',
    gap: 16,
  },
  divider: {
    height: 1.5,
    backgroundColor: theme.Colors.outlineVariant,
    marginVertical: 26,
    opacity: 0.6,
  },
  saveButtonWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  saveButton: {
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  saveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    letterSpacing: 1,
  },
  configButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    gap: 16,
  },
  configIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  configTextWrapper: {
    flex: 1,
  },
  configTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  configSubtitle: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 24,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.DisplaySmall.fontSize,
    fontWeight: '800',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLink: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 18,
    borderRadius: theme.Rounded.lg,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 224, 255, 0.10)',
    borderRightWidth: 4,
    borderRightColor: theme.Colors.primaryContainer,
  },
  sidebarLinkText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
  },
  desktopMain: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1140,
    width: '100%',
    alignSelf: 'center',
    paddingTop: 24,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 32,
  },
  largeTitleContainerDesktop: {
    flex: 1,
  },
  titleLineDesktop: {
    fontSize: theme.Typography.headlineLg.fontSize,
    fontWeight: '900',
    color: theme.Colors.onSurface,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
    fontWeight: '600',
  },
  desktopSaveButtonWrapper: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  desktopSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 14,
    gap: 8,
  },
  desktopSaveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 1,
  },
  desktopFormContainer: {
    flexDirection: 'row',
    gap: 32,
    alignItems: 'flex-start',
  },
  desktopFormLeft: {
    flex: 1.5,
  },
  desktopFormRight: {
    flex: 1.2,
  },
  desktop3DPreviewCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    padding: 24,
    gap: 16,
  },
  desktopPreviewLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
    letterSpacing: 1.2,
  },
  desktop3DContainer: {
    height: 380,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  resetButtonOverlay: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 999,
    zIndex: 10,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  previewInfoRow: {
    marginTop: 8,
  },
  previewName: {
    fontSize: theme.Typography.TitleLarge.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
    marginBottom: 4,
  },
  previewAddress: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 3,
    borderColor: theme.Colors.primaryContainer,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '800',
    fontSize: theme.Typography.bodyLg.fontSize,
  },
});
