import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
    flex: 1,
  },
  desktopInner: {
    maxWidth: 1220,
    width: '100%',
    alignSelf: 'center',
    paddingTop: 24,
    flex: 1,
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  titleContainer: {
    marginTop: 8,
  },
  titleLine: {
    fontSize: theme.Typography.headlineXl.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    lineHeight: 46,
    letterSpacing: -1,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
  },
  gridWrapper: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    overflow: 'hidden',
    marginBottom: 20,
    position: 'relative',
  },
  canvasContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  loadingText: {
    marginTop: 12,
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  isometricContainer: {
    padding: 100,
  },
  detailSheetWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 1000,
    paddingHorizontal: 20,
  },
  detailSheet: {
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    maxHeight: 480,
    overflow: 'hidden',
  },
  sheetContent: {
    padding: 24,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 24,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.DisplaySmall.fontSize,
    fontWeight: '800',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '700',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLinkTextDesktop: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActiveDesktop: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
  },
  desktopMain: {
    flex: 1,
  },
  desktopMainContainer: {
    flex: 1,
    padding: 32,
    gap: 20,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  largeTitleContainer: {
    flex: 1,
  },
  titleLineDesktop: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '900',
    color: theme.Colors.onSurface,
    fontFamily: 'Inter',
  },
  desktopSaveButtonWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  desktopSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 48,
    paddingHorizontal: 24,
  },
  desktopSaveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    fontFamily: 'Inter',
  },
  desktopMainContent: {
    flex: 1,
    flexDirection: 'row',
    gap: 32,
  },
  desktopCanvasColumn: {
    flex: 1.6,
  },
  desktopSidebarColumn: {
    flex: 0.9,
  },
  desktopGridWrapper: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    overflow: 'hidden',
    position: 'relative',
  },
  desktopCard: {
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    padding: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.75)',
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 4,
  },
  sidebarLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    gap: 12,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
  },
  sidebarLinkText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    fontFamily: 'Inter',
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
    fontWeight: '800',
  },
});
