import { StyleSheet } from 'react-native';
import { SerifHeadlineFont } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.Colors.glassStroke,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  compactTitleText: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontFamily: 'Inter',
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  largeTitleContainer: {
    marginBottom: 20,
  },
  titleContainer: {},
  titleLine: {
    fontFamily: SerifHeadlineFont,
    fontSize: 28,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    lineHeight: 36,
    letterSpacing: -0.4,
  },
  propertyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.primaryContainer,
    paddingRight: theme.Spacing.md,
    paddingLeft: 6,
    paddingVertical: 6,
    borderRadius: 100,
    alignSelf: 'flex-start',
    marginTop: 12,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  propertyIconWrapper: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.Spacing.sm,
  },
  propertyNameLabel: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.Spacing.xl,
    paddingTop: 20,
    paddingBottom: 100,
  },
  floorsList: {
    gap: theme.Spacing.md,
  },
  floorCard: {
    borderRadius: 24,
    padding: theme.Spacing.lg,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  floorCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  floorTitle: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  configBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 100,
  },
  configBadgeUnconfigured: {
    backgroundColor: 'rgba(229, 57, 53, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(229, 57, 53, 0.15)',
  },
  configBadgeConfigured: {
    backgroundColor: 'rgba(46, 125, 50, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(46, 125, 50, 0.15)',
  },
  configBadgeText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  configBadgeTextUnconfigured: {
    color: theme.Colors.error,
  },
  configBadgeTextConfigured: {
    color: theme.Colors.primary,
  },
  floorStats: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  statText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  actionButton: {
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: theme.Spacing.sm,
    backgroundColor: 'transparent',
  },
  actionButtonText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  generatePanel: {
    marginTop: 10,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    gap: theme.Spacing.md,
  },
  generatePanelTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: theme.Spacing.xl,
    paddingBottom: theme.Spacing.lg,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.displaySmall.fontSize,
    fontWeight: '800',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLink: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
    paddingHorizontal: 18,
    borderRadius: theme.Rounded.lg,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 224, 255, 0.10)',
    borderRightWidth: 4,
    borderRightColor: theme.Colors.primaryContainer,
  },
  sidebarLinkText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: theme.Spacing.md,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
  },
  desktopMain: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1140,
    width: '100%',
    alignSelf: 'center',
    paddingTop: theme.Spacing.lg,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: theme.Spacing.md,
    marginBottom: theme.Spacing.xl,
  },
  backButtonBadge: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    fontFamily: SerifHeadlineFont,
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
    fontWeight: '600',
  },
  desktopFloorsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.lg,
  },
  desktopFloorCardWrapper: {
    width: '31%',
    minWidth: 320,
  },
  quickCreateRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    width: '100%',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 12,
    overflow: 'hidden',
    height: 48,
    width: 120,
  },
  stepperButton: {
    width: 36,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  stepperInput: {
    width: 48,
    height: '100%',
    textAlign: 'center',
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
    backgroundColor: 'transparent',
  },
  quickCreateInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 1)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
  },
  quickGenerateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: theme.Colors.primary,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 11,
    borderRadius: 8,
  },
  quickGenerateButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
  },
  floorCardDesktop: {
    width: '31%',
    minWidth: 320,
  },
  floorNumberBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.Spacing.md,
  },
  floorNumberText: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
  },
  floorInfo: {
    flex: 1,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    marginTop: theme.Spacing.xs,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.Spacing.sm,
    paddingVertical: theme.Spacing.xs,
    borderRadius: 6,
    gap: theme.Spacing.xs,
  },
  statusConfigured: {
    backgroundColor: 'rgba(46, 125, 50, 0.1)',
  },
  statusNotConfigured: {
    backgroundColor: 'rgba(229, 57, 53, 0.1)',
  },
  statusText: {
    fontSize: theme.Typography.labelSmall.fontSize - 2,
    fontWeight: '700',
  },
  textConfigured: {
    color: theme.Colors.inversePrimary,
  },
  textNotConfigured: {
    color: theme.Colors.error,
  },
  unitCountText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  actionButtonWrapper: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 12,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.sm,
    height: 48,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  editButtonText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
  },
  configureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.sm,
    height: 48,
    borderRadius: 12,
  },
  configureButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
  },
  quickCreateSection: {
    marginTop: theme.Spacing.md,
    paddingTop: theme.Spacing.md,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    opacity: 0.8,
  },
  quickCreateTitle: {
    fontSize: theme.Typography.labelSmall.fontSize - 2,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
    marginBottom: theme.Spacing.sm,
  },
  floorsGridDesktop: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.lg,
  },
});
