import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    createTenantPanel: {
      gap: 12,
      paddingTop: theme.Spacing.sm,
    },
    createTenantHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
      gap: 10,
    },
    createTenantBack: {
      padding: 6,
      borderRadius: 8,
      backgroundColor: isDark ? 'rgba(0, 212, 255, 0.15)' : 'rgba(0, 104, 117, 0.1)',
    },
    createTenantTitle: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '900',
      color: theme.Colors.primary,
      letterSpacing: 1,
    },
    removeTenantButton: {
      padding: 6,
      borderRadius: 10,
      backgroundColor: 'rgba(229, 57, 53, 0.1)',
    },
    inputGroup: {
      gap: 6,
    },
    inputLabel: {
      fontSize: theme.Typography.labelSmall.fontSize - 2,
      fontWeight: '900',
      color: theme.Colors.primary,
      letterSpacing: 1.5,
      fontFamily: 'Inter',
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.Colors.glassFill,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      paddingHorizontal: 14,
      height: 48,
      gap: 10,
    },
    textInput: {
      flex: 1,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.onSurface,
      fontFamily: 'Inter',
      padding: 0,
    },
    statusToggle: {
      paddingVertical: 10,
      paddingHorizontal: theme.Spacing.md,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.Colors.glassStroke,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.Colors.glassFill,
    },
    statusToggleText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '900',
      color: theme.Colors.primary,
      fontFamily: 'Inter',
    },
    statusActiveOccupied: {
      backgroundColor: theme.Colors.primary,
      borderColor: theme.Colors.primary,
    },
    statusTextActive: {
      color: theme.Colors.onPrimary,
    },
    errorText: {
      color: theme.Colors.error,
      fontSize: theme.Typography.bodyMedium.fontSize,
      paddingLeft: theme.Spacing.xs,
      marginTop: theme.Spacing.xs,
      fontFamily: 'Inter',
    },
    errorTextFlat: {
      color: theme.Colors.error,
      fontSize: theme.Typography.bodyMedium.fontSize,
      marginTop: -8,
      marginBottom: 12,
      paddingLeft: theme.Spacing.xs,
      fontFamily: 'Inter',
    },
    tenantListContainer: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      backgroundColor: theme.Colors.glassFill,
      borderRadius: 16,
      borderColor: theme.Colors.glassStroke,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tenantTag: {
      paddingVertical: theme.Spacing.xs,
      paddingHorizontal: theme.Spacing.sm,
      borderRadius: 8,
      backgroundColor: isDark ? 'rgba(0, 212, 255, 0.15)' : 'rgba(0, 104, 117, 0.08)',
    },
    tenantTagText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.primary,
      fontFamily: 'Inter',
    },
    sheetSubtitle: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '700',
      fontFamily: 'Inter',
    },
    warningContainer: {
      flexDirection: 'row',
      gap: 10,
      padding: 12,
      borderRadius: 16,
      backgroundColor: 'rgba(229, 57, 53, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(229, 57, 53, 0.15)',
      alignItems: 'flex-start',
    },
    warningText: {
      flex: 1,
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.error,
      lineHeight: 18,
      fontFamily: 'Inter',
    },
    successContainer: {
      flexDirection: 'row',
      gap: 10,
      padding: 12,
      borderRadius: 16,
      backgroundColor: 'rgba(46, 125, 50, 0.08)',
      borderWidth: 1,
      borderColor: 'rgba(46, 125, 50, 0.15)',
      marginTop: theme.Spacing.sm,
      alignItems: 'flex-start',
    },
    suggestionsContainer: {
      maxHeight: 180,
      backgroundColor: isDark ? '#141D26' : 'rgba(255,255,255,0.95)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(0, 212, 255, 0.2)' : 'rgba(0,104,117,0.15)',
      marginTop: 6,
      shadowColor: theme.Colors.onSurface,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    suggestionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 0.5,
      borderBottomColor: isDark ? 'rgba(0, 212, 255, 0.1)' : 'rgba(0,104,117,0.08)',
      gap: 10,
    },
    suggestionTextContainer: {
      flex: 1,
    },
    suggestionName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.onSurface,
      fontFamily: 'Inter',
    },
    suggestionPhone: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '700',
      fontFamily: 'Inter',
    },
    quickCreatePrompt: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: 'rgba(0, 104, 117, 0.05)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.12)',
      marginBottom: 12,
    },
    quickCreatePromptText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '800',
      color: theme.Colors.primary,
      fontFamily: 'Inter',
      flex: 1,
    },
    quickCreateForm: {
      backgroundColor: 'rgba(0, 104, 117, 0.03)',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.08)',
      padding: 14,
      gap: 12,
      marginBottom: 12,
    },
    quickCreateTitle: {
      fontSize: theme.Typography.labelSmall.fontSize - 1,
      fontWeight: '900',
      color: theme.Colors.primary,
      letterSpacing: 1.5,
      fontFamily: 'Inter',
    },
    quickCreateField: {
      gap: 5,
    },
    quickCreateLabel: {
      fontSize: theme.Typography.labelSmall.fontSize - 3,
      fontWeight: '900',
      color: theme.Colors.primary,
      letterSpacing: 1,
      fontFamily: 'Inter',
    },
    tenantMatchBox: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      backgroundColor: 'rgba(46, 125, 50, 0.05)',
      borderRadius: 16,
      borderColor: 'rgba(46, 125, 50, 0.15)',
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tenantMatchName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.tertiary,
      fontFamily: 'Inter',
    },
    tenantMatchEmail: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontFamily: 'Inter',
    },
  });
