import { StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: { flex: 1 },
  safeArea: { flex: 1 },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 998,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  headerContent: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassFill,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleWrapper: { flex: 1, alignItems: 'center' },
  compactTitleText: {
    color: theme.Colors.onSurface,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontFamily: 'Inter',
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  headerCreateTouch: { borderRadius: 12, overflow: 'hidden' },
  headerCreateInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: theme.Spacing.xs,
  },
  headerCreateText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
  },
  inner: { width: '100%' },
  titleContainer: {
    marginTop: 6,
    marginBottom: theme.Spacing.lg,
  },
  kicker: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: theme.Colors.primary,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  titleActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  screenTitle: {
    fontSize: theme.Typography.headlineLg.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
  },
  screenSubtitle: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    fontWeight: '500',
    lineHeight: 18,
  },
  emptyCard: {
    borderRadius: 24,
    padding: theme.Spacing.xl,
    alignItems: 'center',
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    marginTop: 10,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0, 104, 117, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.Spacing.md,
  },
  emptyTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    marginBottom: theme.Spacing.sm,
  },
  emptySubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    textAlign: 'center',
    marginBottom: theme.Spacing.lg,
    lineHeight: 20,
  },
  createPropertyButton: { borderRadius: 100, overflow: 'hidden' },
  createPropertyGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: 14,
    gap: theme.Spacing.sm,
  },
  createPropertyText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 1,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  listContainer: {
    width: '100%',
  },
  dashedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 188, 212, 0.4)',
    borderRadius: 24,
    paddingVertical: 20,
    backgroundColor: 'rgba(0, 188, 212, 0.03)',
    marginTop: 10,
    gap: 12,
  },
  dashedIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 188, 212, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashedButtonText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.secondary,
    fontWeight: '800',
  },
  desktopShell: { flex: 1 },
  desktopMain: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1080,
    width: '100%',
    alignSelf: 'center',
    paddingTop: theme.Spacing.lg,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.Spacing.xl,
  },
  largeTitleContainer: { flex: 1 },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    color: theme.Colors.onSurface,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    fontWeight: '600',
  },
  desktopCreateButtonWrapper: { borderRadius: 16, overflow: 'hidden' },
  desktopCreateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: 14,
    gap: theme.Spacing.sm,
  },
  desktopCreateButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 1,
  },
});
