import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: { flex: 1 },
  safeArea: { flex: 1 },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  backButton: {
    width: 36, 
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassFill,
    justifyContent: 'center', 
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitle: { fontSize: theme.Typography.bodyLg.fontSize, fontFamily: 'Inter', fontWeight: '800', color: theme.Colors.onSurface },
  headerSubtitle: { fontSize: theme.Typography.BodySmall.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '500', marginTop: 2 },
  
  headerSaveBtnWrapper: {
    borderRadius: 19,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
    marginLeft: 12,
  },
  headerSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    height: 38,
    paddingHorizontal: 16,
  },
  headerSaveText: {
    color: theme.Surface.card,
    fontWeight: '800',
    fontSize: theme.Typography.BodySmall.fontSize,
    letterSpacing: 0.5,
  },
  floatingSaveBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    paddingVertical: 16,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.5)',
    overflow: 'hidden',
  },
  floatingSaveBtn: {
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 6,
  },
  floatingSaveBtnInner: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 18,
  },
  floatingSaveText: {
    color: theme.Surface.card,
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '800',
    letterSpacing: 1,
  },

  filterSection: { paddingHorizontal: 24, marginBottom: 20 },
  
  monthSelector: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 12, 
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    marginTop: 16,
  },
  monthBtn: { padding: 8 },
  monthText: { flex: 1, textAlign: 'center', fontSize: theme.Typography.BodyLarge.fontSize, fontWeight: '700', color: theme.Colors.primary },
  
  listContent: { paddingHorizontal: 24, paddingBottom: 40 },
  emptyState: { padding: 40, alignItems: 'center' },
  emptyText: { color: theme.Colors.onSurfaceVariant, fontSize: theme.Typography.BodyLarge.fontSize },
  
  floorCard: {
    marginBottom: 24,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.8)',
    paddingHorizontal: 24,
    overflow: 'hidden',
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 30,
    elevation: 3,
  },
  floorHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 20 },
  floorHeaderText: { fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '800', color: theme.Colors.primary },
  
  rowCard: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 20,
    borderBottomWidth: 1, borderBottomColor: 'rgba(0, 104, 117, 0.1)',
  },
  rowError: { backgroundColor: 'rgba(254, 226, 226, 0.4)', borderRadius: 12, paddingHorizontal: 8 },
  
  rowLeft: { flex: 2 },
  unitName: { fontSize: theme.Typography.BodyLarge.fontSize, fontWeight: '700', color: theme.Colors.onBackground },
  tenantName: { fontSize: theme.Typography.BodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, marginVertical: 2 },
  prevReading: { fontSize: theme.Typography.LabelSmall.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '600' },
  
  rowMiddle: { flex: 1.5, alignItems: 'flex-end', paddingRight: 12 },
  consumedText: { fontSize: theme.Typography.BodyMedium.fontSize, fontWeight: '700', color: theme.Colors.primary },
  costText: { fontSize: theme.Typography.LabelSmall.fontSize, color: theme.Colors.primary, fontWeight: '600', marginTop: 2 },
  
  rowRight: { flex: 2, alignItems: 'flex-end' },
  input: {
    backgroundColor: theme.Colors.surfaceContainerLowest, 
    borderRadius: 10,
    borderWidth: 1, 
    borderColor: 'rgba(0, 104, 117, 0.15)',
    width: '100%', 
    paddingVertical: 10, 
    paddingHorizontal: 12,
    fontSize: theme.Typography.BodyLarge.fontSize, 
    fontWeight: '600', 
    color: theme.Colors.onBackground, 
    textAlign: 'right',
  },
  inputError: { borderColor: theme.Colors.error, color: theme.Colors.error },
  errorText: { fontSize: theme.Typography.LabelSmall.fontSize, color: theme.Colors.error, fontWeight: '600', marginTop: 4 },

  // Desktop specific styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  desktopMain: {
    flex: 1,
    height: '100%',
  },
  topbar: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 32,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  topbarTabs: {
    flexDirection: 'row',
    gap: 32,
  },
  topbarTab: {
    fontSize: theme.Typography.BodyLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  topbarTabActive: {
    color: theme.Colors.primary,
    fontWeight: '800',
  },
  topbarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  backButtonDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  backButtonTextDesktop: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onBackground,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '700',
    fontSize: theme.Typography.BodyMedium.fontSize,
  },
  desktopContent: {
    paddingBottom: 80,
  },
  desktopInner: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  largeTitleContainer: {
    flex: 1,
  },
  titleLineDesktop: {
    fontSize: theme.Typography.headlineLg.fontSize,
    fontWeight: '800',
    color: theme.Colors.onBackground,
  },
  desktopSubtitle: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
    marginTop: 4,
  },
  desktopSaveButtonWrapper: {
    borderRadius: 23,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  desktopSaveButton: {
    height: 46,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  desktopSaveButtonText: {
    color: theme.Surface.card,
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  desktopFilterRow: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-end',
    marginBottom: 32,
  },
  filterLabelCaps: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
    marginBottom: 8,
  },
  emptyStateCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 24,
    padding: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  desktopGrid: {
    flexDirection: 'row',
    gap: 24,
  },
  desktopLeftColumn: {
    flex: 1.6,
    gap: 24,
  },
  desktopRightColumn: {
    flex: 1,
  },
  summaryCard: {
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 30,
    elevation: 3,
    position: 'sticky',
    top: 24,
  },
  summaryCardTitle: {
    fontSize: theme.Typography.BodySmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
    letterSpacing: 1.5,
    marginBottom: 20,
  },
  summaryMetricsGrid: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  summaryMetricItem: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  summaryMetricLabel: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  summaryMetricValue: {
    fontSize: theme.Typography.TitleLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.onBackground,
  },
  previewDivider: {
    height: 1,
    backgroundColor: 'rgba(0, 104, 117, 0.1)',
    marginVertical: 16,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 6,
  },
  summaryLabel: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    color: theme.Colors.onBackground,
    fontWeight: '700',
  },
  warningAlertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: theme.Colors.tertiaryContainer,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Colors.tertiaryContainer,
    marginTop: 20,
  },
  warningAlertText: {
    fontSize: theme.Typography.BodySmall.fontSize,
    color: theme.Colors.tertiary,
    fontWeight: '600',
    flex: 1,
  },
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.3)',
  },
  pageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  pageButtonDisabled: {
    opacity: 0.4,
  },
  pageButtonText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  pageButtonTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  pageInfoText: {
    fontSize: theme.Typography.BodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onBackground,
  },
  listControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  listControlsRowMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 24,
    gap: 12,
  },
  controlLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 104, 117, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.1)',
  },
  controlLinkText: {
    fontSize: theme.Typography.LabelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  controlSeparator: {
    width: 1,
    height: 12,
    backgroundColor: 'rgba(0, 104, 117, 0.15)',
  },
});
